services:
  monymonty:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monymonty
    restart: unless-stopped
    ports:
    - "8090:80"
    expose:
      - "80"
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  proxy:
    external: true